In [28]:
import requests
import pandas as pd

## Scraping weather news of the area: Panvel, Navi Mumbai

In [62]:
url1 = "http://api.openweathermap.org/data/2.5/forecast?lat=18.990713&lon=73.116844&cnt=200&appid=98e027721603ca32cead5457312b406a"
response1 = requests.get(url1)

In [63]:
json1 = response1.json()

In [64]:
data1 = json1['list']
data1[0]

{'dt': 1619773200,
 'main': {'temp': 305.15,
  'feels_like': 313.56,
  'temp_min': 305.15,
  'temp_max': 308.7,
  'pressure': 1008,
  'sea_level': 1008,
  'grnd_level': 1005,
  'humidity': 70,
  'temp_kf': -3.55},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'clouds': {'all': 20},
 'wind': {'speed': 7.41, 'deg': 272, 'gust': 5.53},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2021-04-30 09:00:00'}

In [65]:
dt = []
temp = []
feels_like = []
temp_min = []
temp_max = []
pressure = []
sea_level = []
grnd_level = []
humidity = []
temp_kf = []
weather_id = []
weather_main = []
weather_description = []
weather_icon = []
clouds_all = []
wind_speed = []
wind_deg = []
wind_gust = []
visibility = []
pop = []
sys_pod = []
dt_txt = []
latitude = []
longitute = []
for i in range(len(data1)):
    dt.append(data[i]['dt'])
    temp.append(data[i]['main']['temp'])
    feels_like.append(data[i]['main']['feels_like'])
    temp_min.append(data[i]['main']['temp_min'])
    temp_max.append(data[i]['main']['temp_max'])
    pressure.append(data[i]['main']['pressure'])
    sea_level.append(data[i]['main']['sea_level'])
    grnd_level.append(data[i]['main']['grnd_level'])
    humidity.append(data[i]['main']['humidity'])
    temp_kf.append(data[i]['main']['temp_kf'])
    weather_id.append(data[i]['weather'][0]['id'])
    weather_main.append(data[i]['weather'][0]['main'])
    weather_description.append(data[i]['weather'][0]['description'])
    weather_icon.append(data[i]['weather'][0]['icon'])
    clouds_all.append(data[i]['clouds']['all'])
    wind_speed.append(data[i]['wind']['speed'])
    wind_deg.append(data[i]['wind']['deg'])
    wind_gust.append(data[i]['wind']['gust'])
    visibility.append(data[i]['visibility'])
    pop.append(data[i]['pop'])
    sys_pod.append(data[i]['sys']['pod'])
    dt_txt.append(data[i]['dt_txt'])
    latitude.append(18.990713)
    longitute.append(73.116844)

## Scraping weather news of the area: Vashi, Navi Mumbai

In [66]:
url2 = "http://api.openweathermap.org/data/2.5/forecast?lat=19.0745&lon=72.9978&cnt=200&appid=98e027721603ca32cead5457312b406a"
response2 = requests.get(url2)

In [67]:
json2 = response2.json()

In [68]:
data2 = json2['list']
data2[0]

{'dt': 1619773200,
 'main': {'temp': 305.15,
  'feels_like': 313.56,
  'temp_min': 305.15,
  'temp_max': 306.43,
  'pressure': 1008,
  'sea_level': 1008,
  'grnd_level': 1006,
  'humidity': 70,
  'temp_kf': -1.28},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'clouds': {'all': 20},
 'wind': {'speed': 7.03, 'deg': 273, 'gust': 5.77},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2021-04-30 09:00:00'}

In [69]:
for i in range(len(data2)):
    dt.append(data[i]['dt'])
    temp.append(data[i]['main']['temp'])
    feels_like.append(data[i]['main']['feels_like'])
    temp_min.append(data[i]['main']['temp_min'])
    temp_max.append(data[i]['main']['temp_max'])
    pressure.append(data[i]['main']['pressure'])
    sea_level.append(data[i]['main']['sea_level'])
    grnd_level.append(data[i]['main']['grnd_level'])
    humidity.append(data[i]['main']['humidity'])
    temp_kf.append(data[i]['main']['temp_kf'])
    weather_id.append(data[i]['weather'][0]['id'])
    weather_main.append(data[i]['weather'][0]['main'])
    weather_description.append(data[i]['weather'][0]['description'])
    weather_icon.append(data[i]['weather'][0]['icon'])
    clouds_all.append(data[i]['clouds']['all'])
    wind_speed.append(data[i]['wind']['speed'])
    wind_deg.append(data[i]['wind']['deg'])
    wind_gust.append(data[i]['wind']['gust'])
    visibility.append(data[i]['visibility'])
    pop.append(data[i]['pop'])
    sys_pod.append(data[i]['sys']['pod'])
    dt_txt.append(data[i]['dt_txt'])
    latitude.append(19.0745)
    longitute.append(72.9978)

## Scraping weather news of the area: Belapur, Navi Mumbai

In [70]:
url3 = "http://api.openweathermap.org/data/2.5/forecast?lat=19.0237&lon=73.0404&cnt=200&appid=98e027721603ca32cead5457312b406a"
response3 = requests.get(url3)

In [71]:
json3 = response3.json()

In [72]:
data3 = json3['list']
data3[0]

{'dt': 1619773200,
 'main': {'temp': 305.15,
  'feels_like': 313.56,
  'temp_min': 305.15,
  'temp_max': 306.68,
  'pressure': 1008,
  'sea_level': 1008,
  'grnd_level': 1006,
  'humidity': 70,
  'temp_kf': -1.53},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02d'}],
 'clouds': {'all': 20},
 'wind': {'speed': 7.22, 'deg': 273, 'gust': 5.88},
 'visibility': 10000,
 'pop': 0,
 'sys': {'pod': 'd'},
 'dt_txt': '2021-04-30 09:00:00'}

In [73]:
for i in range(len(data3)):
    dt.append(data[i]['dt'])
    temp.append(data[i]['main']['temp'])
    feels_like.append(data[i]['main']['feels_like'])
    temp_min.append(data[i]['main']['temp_min'])
    temp_max.append(data[i]['main']['temp_max'])
    pressure.append(data[i]['main']['pressure'])
    sea_level.append(data[i]['main']['sea_level'])
    grnd_level.append(data[i]['main']['grnd_level'])
    humidity.append(data[i]['main']['humidity'])
    temp_kf.append(data[i]['main']['temp_kf'])
    weather_id.append(data[i]['weather'][0]['id'])
    weather_main.append(data[i]['weather'][0]['main'])
    weather_description.append(data[i]['weather'][0]['description'])
    weather_icon.append(data[i]['weather'][0]['icon'])
    clouds_all.append(data[i]['clouds']['all'])
    wind_speed.append(data[i]['wind']['speed'])
    wind_deg.append(data[i]['wind']['deg'])
    wind_gust.append(data[i]['wind']['gust'])
    visibility.append(data[i]['visibility'])
    pop.append(data[i]['pop'])
    sys_pod.append(data[i]['sys']['pod'])
    dt_txt.append(data[i]['dt_txt'])
    latitude.append(19.0237)
    longitute.append(73.0404)

## Creating the dataset

In [74]:
d = {'dt': dt, 
     'latitude': latitude,
     'longitute': longitute,
     'temp': temp, 
     'feels_like': feels_like,
    'temp_min ':temp_min,
     'temp_max': temp_max, 
        'pressure':pressure,
     'sea_level': sea_level, 
     'grnd_level': grnd_level,
     'humidity': humidity,
       'temp_kf': temp_kf,
    'weather_id': weather_id,
    'weather_main': weather_main,
    'weather_description': weather_description,
    'weather_icon': weather_icon,
    'clouds_all': clouds_all,
    'wind_speed': wind_speed,
    'wind_deg': wind_deg,
    'wind_gust': wind_gust,
    'visibility': visibility,
    'pop': pop,
    'sys_pod': sys_pod,
    'dt_txt': dt_txt}
df = pd.DataFrame(data = d)

In [57]:
df.head()

,dt,latitude,longitute,temp,feels_like,temp_min,temp_max,pressure,sea_level,grnd_level,...,weather_description,weather_icon,clouds_all,wind_speed,wind_deg,wind_gust,visibility,pop,sys_pod,dt_txt
0,1619773200,18.990713,73.116844,305.15,312.15,305.15,308.70,1009,1009,1005,...,few clouds,02d,20,7.41,272,5.53,10000,0.00,d,2021-04-30 09:00:00
1,1619784000,18.990713,73.116844,305.64,311.07,305.64,306.61,1008,1008,1004,...,scattered clouds,03d,28,5.54,279,6.64,10000,0.00,d,2021-04-30 12:00:00
2,1619794800,18.990713,73.116844,304.62,307.97,304.36,304.62,1008,1008,1006,...,scattered clouds,03n,47,1.49,279,2.00,10000,0.08,n,2021-04-30 15:00:00
3,1619805600,18.990713,73.116844,303.04,305.58,303.04,303.04,1009,1009,1007,...,scattered clouds,03n,49,2.45,298,3.87,10000,0.08,n,2021-04-30 18:00:00
4,1619816400,18.990713,73.116844,302.27,304.88,302.27,302.27,1007,1007,1005,...,broken clouds,04n,55,0.20,236,1.71,10000,0.08,n,2021-04-30 21:00:00

In [60]:
df.describe()

,dt,latitude,longitute,temp,feels_like,temp_min,temp_max,pressure,sea_level,grnd_level,humidity,temp_kf,weather_id,clouds_all,wind_speed,wind_deg,wind_gust,visibility,pop
count,1.200000e+02,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.0,120.000000
mean,1.619984e+09,19.029638,73.051681,304.223833,306.790750,304.217167,304.293583,1007.441667,1007.441667,1006.400000,55.416667,-0.063083,801.216667,26.841667,3.342417,261.025000,3.708250,10000.0,0.033583
std,1.251914e+05,0.034607,0.049456,2.445839,2.497382,2.445142,2.504374,1.442429,1.442429,1.463276,11.172132,0.386818,1.291103,28.818469,2.092169,92.713842,1.796807,0.0,0.054938
min,1.619773e+09,18.990713,72.997800,299.840000,301.990000,299.840000,299.840000,1004.000000,1004.000000,1003.000000,31.000000,-3.550000,800.000000,0.000000,0.140000,2.000000,0.830000,10000.0,0.000000
25%,1.619878e+09,18.990713,72.997800,302.250000,304.930000,302.250000,302.250000,1007.000000,1007.000000,1005.000000,48.750000,0.000000,800.000000,2.000000,1.860000,266.000000,2.335000,10000.0,0.000000
50%,1.619984e+09,19.023700,73.040400,303.785000,306.030000,303.785000,303.785000,1008.000000,1008.000000,1007.000000,56.500000,0.000000,801.000000,20.000000,2.450000,285.000000,3.285000,10000.0,0.000000
75%,1.620089e+09,19.074500,73.116844,305.755000,308.637500,305.755000,306.152500,1008.000000,1008.000000,1007.250000,65.000000,0.000000,802.000000,45.500000,4.847500,309.500000,4.952500,10000.0,0.052500
max,1.620194e+09,19.074500,73.116844,310.280000,313.560000,310.280000,310.280000,1010.000000,1010.000000,1009.000000,77.000000,0.310000,804.000000,95.000000,7.530000,356.000000,8.240000,10000.0,0.230000

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dt                   120 non-null    int64
 1   latitude             120 non-null    float64
 2   longitute            120 non-null    float64
 3   temp                 120 non-null    float64
 4   feels_like           120 non-null    float64
 5   temp_min             120 non-null    float64
 6   temp_max             120 non-null    float64
 7   pressure             120 non-null    int64
 8   sea_level            120 non-null    int64
 9   grnd_level           120 non-null    int64
 10  humidity             120 non-null    int64
 11  temp_kf              120 non-null    float64
 12  weather_id           120 non-null    int64
 13  weather_main         120 non-null    object
 14  weather_description  120 non-null    object
 15  weather_icon         120 non-null    object
 16  clouds_all           120 non-null    int64
 17  wind_speed           120 non-null    float64
 18  wind_deg             120 non-null    int64
 19  wind_gust            120 non-null    float64
 20  visibility           120 non-null    int64
 21  pop                  120 non-null    float64
 22  sys_pod              120 non-null    object
 23  dt_txt               120 non-null    object
dtypes: float64(10), int64(9), object(5)
memory usage: 22.6+ KB

In [59]:
df.shape

(120, 24)